os: linux
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
  allow_failures:
    - os: osx
install: pip install tox-travis
script: tox
