os: linux
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - language: generic
      os: osx
      install: pip2 install tox-travis
  allow_failures:
    - os: osx
install: pip install tox-travis
script: tox
